#!/usr/bin/env bash
#
# Stitch the four beats + voice-over + captions into the final <=90s
# demo video for OKX.AI Genesis.
#
# Input beat clips (drop them in this directory before running):
#   beat1_marketplace.mp4        20s — OKX.AI Coach card / OKLink XLayer explorer
#   beat2_402_challenge.mp4      ~14s — vhs terminal
#   beat3_settlement.mp4         30s — signing/settlement flow slide
#   beat4_asp_identity.mp4       15s — vhs terminal + OKLink cutaway
#
# VO input:
#   vo-raw.wav        recorded real-voice per vo-script.md
#
# Caption inputs (auto-generated by build_captions.py if missing):
#   caption1.png … caption4.png
#
# Output:
#   demo-okx-genesis.mp4         <=90s final, ready for the Google Form,
#                                with lower-third captions burned in
#
# Two ffmpeg passes:
#   1. Concat FILTER (not demuxer) — the demuxer stream-copies and silently
#      drops frames when the inputs have mismatched res/fps (PIL slides
#      1920x1080@30 vs vhs terminals 1440x{480,540}@25). Filter normalizes
#      each beat to 1080p / 30 fps then concatenates.
#   2. Caption overlay — this ffmpeg build (Homebrew 8.1.1) ships without
#      libass, so instead of the `subtitles`/`ass` filter we overlay four
#      PIL-rendered lower-third PNGs with time-gated `overlay` filters
#      (`enable='between(t,X,Y)'`), matching the [[feedback-demo-video-
#      production]] pattern. `-loop 1 -t 80` caps each image loop so
#      ffmpeg exits when the underlying video ends.

set -euo pipefail

cd "$(dirname "$0")"

REQ=(beat1_marketplace.mp4 beat2_402_challenge.mp4 beat3_settlement.mp4 beat4_asp_identity.mp4 vo-raw.wav)
for f in "${REQ[@]}"; do
    [[ -f "$f" ]] || { echo "missing: $f"; exit 1; }
done

# Auto-render caption PNGs if the user hasn't already.
if [[ ! -f caption1.png || ! -f caption2.png || ! -f caption3.png || ! -f caption4.png ]]; then
    echo "captions missing — rendering via build_captions.py"
    "$(dirname "$(dirname "$(pwd)")")/agent/.venv/bin/python3" build_captions.py \
        || python3 build_captions.py
fi

# ---- Pass 1: concat the four beats + attach VO, write a working file.
STAGE1=demo-okx-genesis.stage1.mp4
ffmpeg -y \
    -i beat1_marketplace.mp4 \
    -i beat2_402_challenge.mp4 \
    -i beat3_settlement.mp4 \
    -i beat4_asp_identity.mp4 \
    -i vo-raw.wav \
    -filter_complex "\
        [0:v]scale=1920:1080:force_original_aspect_ratio=decrease,pad=1920:1080:(ow-iw)/2:(oh-ih)/2:color=black,fps=30,setsar=1[v0]; \
        [1:v]scale=1920:1080:force_original_aspect_ratio=decrease,pad=1920:1080:(ow-iw)/2:(oh-ih)/2:color=black,fps=30,setsar=1[v1]; \
        [2:v]scale=1920:1080:force_original_aspect_ratio=decrease,pad=1920:1080:(ow-iw)/2:(oh-ih)/2:color=black,fps=30,setsar=1[v2]; \
        [3:v]scale=1920:1080:force_original_aspect_ratio=decrease,pad=1920:1080:(ow-iw)/2:(oh-ih)/2:color=black,fps=30,setsar=1[v3]; \
        [v0][v1][v2][v3]concat=n=4:v=1:a=0[v]; \
        [4:a]adelay=0|0[a]" \
    -map "[v]" -map "[a]" \
    -c:v libx264 -preset medium -crf 20 -pix_fmt yuv420p -profile:v high -level 4.1 -movflags +faststart \
    -c:a aac -b:a 192k -shortest \
    "$STAGE1"

# ---- Pass 2: overlay the four captions at their timed windows.
# Windows match vo-script.md ± 1 s slack for beat-boundary breathing room.
ffmpeg -y -i "$STAGE1" \
    -loop 1 -t 80 -i caption1.png \
    -loop 1 -t 80 -i caption2.png \
    -loop 1 -t 80 -i caption3.png \
    -loop 1 -t 80 -i caption4.png \
    -filter_complex "\
        [0:v][1:v]overlay=x=(W-w)/2:y=H-h-60:enable='between(t,3,19)'[o1]; \
        [o1][2:v]overlay=x=(W-w)/2:y=H-h-60:enable='between(t,23,33)'[o2]; \
        [o2][3:v]overlay=x=(W-w)/2:y=H-h-60:enable='between(t,36,63)'[o3]; \
        [o3][4:v]overlay=x=(W-w)/2:y=H-h-60:enable='between(t,65,78)'[v]" \
    -map "[v]" -map "0:a" -shortest \
    -c:v libx264 -preset medium -crf 20 -pix_fmt yuv420p -profile:v high -level 4.1 -movflags +faststart \
    -c:a copy \
    demo-okx-genesis.mp4

rm -f "$STAGE1"

duration=$(ffprobe -v error -show_entries format=duration -of csv=p=0 demo-okx-genesis.mp4)
awk -v d="$duration" 'BEGIN { if (d > 90.0) { print "FAIL: duration " d "s exceeds 90s cap"; exit 1 } else print "OK: duration " d "s under 90s cap" }'
